### PR TITLE
Remove version range Support Library version

### PR DESCRIPTION
**Pull request by ianhanniballake**
Using a version range for the Support Library version leads to unpredictable builds and causes apps to be automatically updated to the newest version of the Support Library annotations even if they would otherwise be using an older version. Even for the Annotations alone, there can be [breaking changes](https://issuetracker.google.com/issues/75985001) that this can introduce.

As the Support Library goes through alpha and beta releases tied to new versions of Android, this also can force developers onto alpha or beta builds. For example, right now, the latest published version is `28.0.0-alpha1` - something that most developers do not want to rely on yet.

Gradle will automatically update to the latest version of the Support Library included by any library, so the version range wasn't really adding anything but non-hermetic builds.

### CODE REVIEW

**Comment by ccjernigan** [comment]
Thanks Ian!  I'm totally with you on the non-hermetic builds.

Maybe I'm confused with how transitive dependencies work, especially since this project is a library consumed by others.  Can you help me with a question?

I thought that if I set an exact version of the support library (let's say 19.0.0) in this project, that would enforce the same support library version on consumers of this project, unless they added `force = true` to the support library declaration in their build.gradle for the support library.  That's why I set a minimum but left the max version unconstrained for consumers.

An example of a consuming project would be https://github.com/twofortyfouram/android-toast-setting-plugin-for-locale which sets the support library to a range ]25.0.0,26[.  So if we set the plugin-api-for-locale to require 19.0.0, wouldn't that cause the toast app to fail to build due to version conflicts?

Is there something special happening for support library dependencies?  Or am I misunderstanding the Gradle documentation?

**Comment by ianhanniballake** [comment]
What you're thinking of is `]19.0.0,19.0.0[`, where you must use exactly a single version and nothing else is compatible.

There's two things at work:
- Gradle always chooses the highest version that dependencies request as per the [transitive dependency documentation](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:dependency_constraints) - i.e., when given 1.0 and 2.0, Gradle will choose 2.0 for that dependency.
- "If the dependency is declared as a dynamic version (like 1.+), Gradle will resolve this to the highest available concrete version (like 1.2) in the repository." from the [dependency resolution documentation](https://docs.gradle.org/current/userguide/introduction_dependency_management.html#sec:dependency_resolution)

Therefore when using a version range in your transitive dependency, Gradle resolves it as the highest version possible. An open ended version range just means "always pick the very latest from the repository". From Gradle's point of view, this means your dependency always wants the latest, no matter what other dependencies want (since Gradle always picks the highest version requested).

If instead, you use a fixed version number, there's two scenarios to take into account:
1. There's no other library that requests a higher version of that same dependency. In that case, the fixed version is used.
2. There's a library that requests a higher version of the same dependency. In that case, the version requested by the other library takes precedence and the dependency is upgraded to that higher version.

**Comment by ianhanniballake** [comment]
Any update on this?

**Comment by ccjernigan** [comment]
Thanks for your help with identifying this issue.  I pushed a new revision of the library artifact to Bintray, so that should resolve the issue for consumers of the library.

**Comment by ianhanniballake** [comment]
What revision is this fixed in? I'm not seeing the expected 1.0.3 version or the equivalent.

**Comment by ccjernigan** [comment]
There is a version 1.0.4 published on Bintray which fixes this.  That version doesn't exist in this GitHub repo. Everything is also in the process of being migrated to a monorepo which is a bit of a work in progress: https://github.com/twofortyfouram/android-monorepo

**Comment by ianhanniballake** [comment]
Thanks, I can confirm that 1.0.4 fixes the issue and I'm no longer auto-updated to the latest Support Library version.

**Comment by ccjernigan** [comment]
And thank you for identifying this issue!

**Pull request closed without merging**
